version: '2'

services:

 nginx-user-management:
   image: shakyshane/nginx-cors
   ports:
     - 5000:80
   environment:
     - TARGET_DOMAIN=user-management:5000

 gtw:
   restart: always
   build:
     context: ./src/nginx-oauth2-introspection-docker
     args:
       - TARGET=http://nginx-user-management
       - CLIENT_ID=KZ6vazBeDMLy
       - CLIENT_SECRET=36d9152fced0a9b9eccb4d1030cae260d79f35de7a4705838ad430eb
       - OAUTH_TOKEN_ENDPOINT=http://nginx-identity-server:8040/introspection
   ports:
     - 5050:80

